# version: "3"
# services:
#   web:
#     container_name: test-sales
#     # volumes:
#     #   - ./nginx.conf:/etc/nginx/nginx.conf
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     ports: 
#       - 2935:80
    
    
version: "3"
services:
  web:
    container_name: SalesNet-pwa
    build: .
    ports: 
      - 2935:80
