import React from 'react'

export default function EmpListDropdown() {
    return (
        <>

            <option value={5}>Account Manager</option>
            <option value={6}>Account Manager Automation</option>
            <option value={52}>Account Manager EDA</option>
            <option value={53}>Account Manager Instrumentation</option>
            <option value={114}>Account Manager NI</option>
            <option value={137}>Account Manager-ISG</option>
            <option value={154}>Accounts and Administration Executive </option>
            <option value={8}>Admin Executive</option>
            <option value={3}>Administrator</option>
            <option value={205}>AGM (IT-Solutions)</option>
            <option value={210}>Android Developer </option>
            <option value={202}>Application Engineer - PSG</option>
            <option value={138}>Application Engineer - VisSim</option>
            <option value={130}>Application Head (Technical - Manager)</option>
            <option value={203}>Assistant Manager GIS Project </option>
            <option value={54}>Assistant Manager Project</option>
            <option value={102}>Assistant Manager-Technical</option>
            <option value={9}>Associate Manager Admin</option>
            <option value={10}>Associate Manager F & A</option>
            <option value={11}>Associate Manager HR</option>
            <option value={55}>Associate Manager S & M</option>
            <option value={157}>Associate Technical Manager</option>
            <option value={12}>Associate Vice President Technical </option>
            <option value={56}>Associate Vice President Technical </option>
            <option value={171}>Asst. Manager- Power System</option>
            <option value={178}>Asst. Vice President</option>
            <option value={182}>AVP - Automation</option>
            <option value={181}>AVP - EDA</option>
            <option value={179}>AVP Sales - A & D</option>
            <option value={180}>AVP Sales - Private Account</option>
            <option value={147}>Branch Manager - Chennai</option>
            <option value={145}>Branch Manager - Pune</option>
            <option value={106}>Branch Manager- Hyderabad</option>
            <option value={13}>Branch Manager- Kolkata</option>
            <option value={105}>Branch Manager-Delhi</option>
            <option value={150}>Business Development Executive</option>
            <option value={14}>Business Development Manager</option>
            <option value={57}>CEO (Chief Executive Officer)</option>
            <option value={146}>Chief Administrator</option>
            <option value={16}>Chief Technical officer</option>
            <option value={58}>Client Relationship Officer </option>
            <option value={15}>Country Manager Mentor</option>
            <option value={17}>Customer Relationship Manager</option>
            <option value={19}>Design Engnieer </option>
            <option value={156}>Developer</option>
            <option value={191}>Draftsman</option>
            <option value={125}>Driver</option>
            <option value={18}>Dy Manager Corporate Affairs</option>
            <option value={59}>Dy Manager Project </option>
            <option value={20}>Dy Manager S&M </option>
            <option value={60}>Engineer -GIS</option>
            <option value={97}>Engineer GIS</option>
            <option value={21}>Engineer Project</option>
            <option value={22}>Engineer Technical </option>
            <option value={168}>Engineer-Power System</option>
            <option value={177}>Executive - Director</option>
            <option value={108}>Executive Accounts</option>
            <option value={61}>Executive Assistant</option>
            <option value={118}>Executive HR & Marketing</option>
            <option value={62}>Executive Technical </option>
            <option value={25}>FAE</option>
            <option value={174}>FAE - CREO</option>
            <option value={173}>FAE - Electrical</option>
            <option value={175}>FAE - Reliability</option>
            <option value={185}>FAE - WQS</option>
            <option value={26}>FAE -PCB</option>
            <option value={65}>FAE -Relex</option>
            <option value={167}>FAE -VLSI</option>
            <option value={64}>FAE- EDA</option>
            <option value={136}>FAE-ASG</option>
            <option value={23}>FAE-Automation </option>
            <option value={63}>FAE-Collabnet</option>
            <option value={24}>FAE-Instrumentation</option>
            <option value={165}>FAE-Mechanical</option>
            <option value={91}>FAE-NI</option>
            <option value={89}>FAE-Power-ASG</option>
            <option value={113}>FAE-Texas Instruments</option>
            <option value={27}>Front Office Executive</option>
            <option value={107}>General Manager - ISG</option>
            <option value={28}>General Manager -Design Services</option>
            <option value={66}>GIS Executive</option>
            <option value={29}>HR Executive</option>
            <option value={200}>HR Intern</option>
            <option value={208}>Internal coordinator </option>
            <option value={207}>Jr HR Executive </option>
            <option value={115}>Jr. Admin Executive</option>
            <option value={67}>Jr. Engineer Project </option>
            <option value={117}>Jr. Executive Accounts</option>
            <option value={68}>Management Trainee </option>
            <option value={1}>Manager</option>
            <option value={148}>Manager (Application & Support)</option>
            <option value={172}>Manager (IT-Solutions)</option>
            <option value={184}>Manager - Corporate - F & A</option>
            <option value={183}>Manager - Corporate Affairs</option>
            <option value={121}>Manager Hardware Engineering</option>
            <option value={69}>Managing Director</option>
            <option value={123}>Marketing Communication</option>
            <option value={120}>Marketing Engineer</option>
            <option value={111}>Marketing Engineer-PSG</option>
            <option value={142}>Marketing Manager</option>
            <option value={193}>National Head-Private</option>
            <option value={110}>Network Administrator</option>
            <option value={116}>Office Assistant</option>
            <option value={129}>PCB Design Engineer</option>
            <option value={32}>President </option>
            <option value={161}>Product Head (A&D-Country Manager)</option>
            <option value={127}>Product Head (Account Manager - EDA)</option>
            <option value={158}>Product Head (Associate Vice President (ESG))</option>
            <option value={124}>Product Head (Country Manager)</option>
            <option value={126}>Product Head (Sales Manager South)</option>
            <option value={162}>Product Head (Strategy Sales-Country Manager)</option>
            <option value={144}>Product Head Sr. Sales Manager (ESG)</option>

        </>
    )
}
