import React from 'react'

export default function EmpListDropdown() {
    return (
        <>

            <option value={5}>Account Manager</option>
            <option value={6}>Account Manager Automation</option>
            <option value={52}>Account Manager EDA</option>
            <option value={53}>Account Manager Instrumentation</option>
            <option value={114}>Account Manager NI</option>
            <option value={137}>Account Manager-ISG</option>
            <option value={154}>Accounts and Administration Executive </option>
            <option value={8}>Admin Executive</option>
            <option value={3}>Administrator</option>
            <option value={205}>AGM (IT-Solutions)</option>
            <option value={210}>Android Developer </option>
            <option value={202}>Application Engineer - PSG</option>
            <option value={138}>Application Engineer - VisSim</option>
            <option value={130}>Application Head (Technical - Manager)</option>
            <option value={203}>Assistant Manager GIS Project </option>
            <option value={54}>Assistant Manager Project</option>
            <option value={102}>Assistant Manager-Technical</option>
            <option value={9}>Associate Manager Admin</option>
            <option value={10}>Associate Manager F & A</option>
            <option value={11}>Associate Manager HR</option>
            <option value={55}>Associate Manager S & M</option>
            <option value={157}>Associate Technical Manager</option>
            <option value={12}>Associate Vice President Technical </option>
            <option value={56}>Associate Vice President Technical </option>
            <option value={171}>Asst. Manager- Power System</option>
            <option value={178}>Asst. Vice President</option>
            <option value={182}>AVP - Automation</option>
            <option value={181}>AVP - EDA</option>
            <option value={179}>AVP Sales - A & D</option>
            <option value={180}>AVP Sales - Private Account</option>
            <option value={147}>Branch Manager - Chennai</option>
            <option value={145}>Branch Manager - Pune</option>
            <option value={106}>Branch Manager- Hyderabad</option>
            <option value={13}>Branch Manager- Kolkata</option>
            <option value={105}>Branch Manager-Delhi</option>
            <option value={150}>Business Development Executive</option>
            <option value={14}>Business Development Manager</option>
            <option value={57}>CEO (Chief Executive Officer)</option>
            <option value={146}>Chief Administrator</option>
            <option value={16}>Chief Technical officer</option>
            <option value={58}>Client Relationship Officer </option>
            <option value={15}>Country Manager Mentor</option>
            <option value={17}>Customer Relationship Manager</option>
            <option value={19}>Design Engnieer </option>
            <option value={156}>Developer</option>
            <option value={191}>Draftsman</option>
            <option value={125}>Driver</option>
            <option value={18}>Dy Manager Corporate Affairs</option>
            <option value={59}>Dy Manager Project </option>
            <option value={20}>Dy Manager S&M </option>
            <option value={60}>Engineer -GIS</option>
            <option value={97}>Engineer GIS</option>
            <option value={21}>Engineer Project</option>
            <option value={22}>Engineer Technical </option>
            <option value={168}>Engineer-Power System</option>
            <option value={177}>Executive - Director</option>
            <option value={108}>Executive Accounts</option>
            <option value={61}>Executive Assistant</option>
            <option value={118}>Executive HR & Marketing</option>
            <option value={62}>Executive Technical </option>
            <option value={25}>FAE</option>
            <option value={174}>FAE - CREO</option>
            <option value={173}>FAE - Electrical</option>
            <option value={175}>FAE - Reliability</option>
            <option value={185}>FAE - WQS</option>
            <option value={26}>FAE -PCB</option>
            <option value={65}>FAE -Relex</option>
            <option value={167}>FAE -VLSI</option>
            <option value={64}>FAE- EDA</option>
            <option value={136}>FAE-ASG</option>
            <option value={23}>FAE-Automation </option>
            <option value={63}>FAE-Collabnet</option>
            <option value={24}>FAE-Instrumentation</option>
            <option value={165}>FAE-Mechanical</option>
            <option value={91}>FAE-NI</option>
            <option value={89}>FAE-Power-ASG</option>
            <option value={113}>FAE-Texas Instruments</option>
            <option value={27}>Front Office Executive</option>
            <option value={107}>General Manager - ISG</option>
            <option value={28}>General Manager -Design Services</option>
            <option value={66}>GIS Executive</option>
            <option value={29}>HR Executive</option>
            <option value={200}>HR Intern</option>
            <option value={208}>Internal coordinator </option>
            <option value={207}>Jr HR Executive </option>
            <option value={115}>Jr. Admin Executive</option>
            <option value={67}>Jr. Engineer Project </option>
            <option value={117}>Jr. Executive Accounts</option>
            <option value={68}>Management Trainee </option>
            <option value={1}>Manager</option>
            <option value={148}>Manager (Application & Support)</option>
            <option value={172}>Manager (IT-Solutions)</option>
            <option value={184}>Manager - Corporate - F & A</option>
            <option value={183}>Manager - Corporate Affairs</option>
            <option value={121}>Manager Hardware Engineering</option>
            <option value={69}>Managing Director</option>
            <option value={123}>Marketing Communication</option>
            <option value={120}>Marketing Engineer</option>
            <option value={111}>Marketing Engineer-PSG</option>
            <option value={142}>Marketing Manager</option>
            <option value={193}>National Head-Private</option>
            <option value={110}>Network Administrator</option>
            <option value={116}>Office Assistant</option>
            <option value={129}>PCB Design Engineer</option>
            <option value={32}>President </option>
            <option value={161}>Product Head (A&D-Country Manager)</option>
            <option value={127}>Product Head (Account Manager - EDA)</option>
            <option value={158}>Product Head (Associate Vice President (ESG))</option>
            <option value={124}>Product Head (Country Manager)</option>
            <option value={126}>Product Head (Sales Manager South)</option>
            <option value={162}>Product Head (Strategy Sales-Country Manager)</option>
            <option value={144}>Product Head Sr. Sales Manager (ESG)</option>
            <option value={163}>Project Coordinator</option>
            <option value={196}>Project Manager</option>
            <option value={33}>Regional  Manager </option>
            <option value={186}>Regional Head</option>
            <option value={70}>Regional Manager Automation</option>
            <option value={71}>Regional Manager EDA</option>
            <option value={72}>Regional Manager Instrumentation</option>
            <option value={35}>Sales Engineer </option>
            <option value={131}>Sales Engineer - PCB</option>
            <option value={73}>Sales Engineer Automation</option>
            <option value={74}>Sales Engineer EDA</option>
            <option value={36}>Sales Engineer Govt</option>
            <option value={37}>Sales Engineer Instrumentation</option>
            <option value={75}>Sales Engineer S & M</option>
            <option value={139}>Sales Engineer- ASG</option>
            <option value={90}>Sales Engineer-NI</option>
            <option value={93}>Sales Engineer-PSG</option>
            <option value={34}>Sales Manager North</option>
            <option value={38}>Sales Manager South</option>
            <option value={39}>Sr. Account Manager</option>
            <option value={92}>Sr. Account Manager Instrumentation</option>
            <option value={286}>Sr. Account Manager-ESG</option>
            <option value={98}>Sr. Admin Officer</option>
            <option value={195}>Sr. Draftsman</option>
            <option value={99}>Sr. Engineer Project</option>
            <option value={76}>Sr. Engineer Technical </option>
            <option value={169}>Sr. Engineer-Power System</option>
            <option value={149}>Sr. Executive - Accounts</option>
            <option value={100}>Sr. Executive F & A</option>
            <option value={41}>Sr. FAE</option>
            <option value={80}>Sr. FAE Automation</option>
            <option value={81}>Sr. FAE EDA</option>
            <option value={94}>Sr. FAE Instrumentation</option>
            <option value={82}>Sr. FAE NI</option>
            <option value={166}>Sr. FAE- Mechanical</option>
            <option value={88}>Sr. HR Executive</option>
            <option value={143}>Sr. ISR</option>
            <option value={159}>Sr. Manager</option>
            <option value={77}>Sr. Manager GIS</option>
            <option value={78}>Sr. Manager S&M </option>
            <option value={187}>Sr. Marketing Engineer</option>
            <option value={128}>Sr. Marketing Engineer-PSG</option>
            <option value={168}>Sr. Network Administrator</option>
            <option value={152}>Sr. Product Specialist </option>
            <option value={140}>Sr. Project Engineer</option>
            <option value={122}>Sr. Regional Manager (AP and West India)</option>
            <option value={42}>Sr. Sales Engineer</option>
            <option value={95}>Sr. Sales Engineer EDA</option>
            <option value={96}>Sr. Sales Engineer Instrumentation</option>
            <option value={188}>Sr. Sales Manager</option>
            <option value={170}>Sr. Technical Manager</option>
            <option value={194}>Sr. Technical Manager</option>
            <option value={43}>Sr.Admin  Executive</option>
            <option value={44}>Sr.Design Engineer </option>
            <option value={45}>Sr.Executive Accounts</option>
            <option value={83}>Sr.FAE Collabnet</option>
            <option value={84}>Sr.FAE-Relex</option>
            <option value={85}>Sr.GIS Executive</option>
            <option value={86}>Sr.Manager Project</option>
            <option value={45}>Sr.Sales Engineer </option>
            <option value={47}>Sr.Sales Engineer Automation</option>
            <option value={48}>Sr.Sales Engineer- S& M</option>
            <option value={87}>Supervisor </option>
            <option value={109}>System Admin</option>
            <option value={104}>Team Lead Design (Technical Manager)</option>
            <option value={112}>Tech Support Power System</option>
            <option value={141}>Technical Consultant</option>
            <option value={103}>Technical Manager</option>
            <option value={49}>Technical Manager -HDL</option>
            <option value={209}>Technical Support (Installation & Licensing) </option>
            <option value={50}>Technical Support Engineer </option>
            <option value={151}>Vice President</option>

        </>
    )
}
